#!/usr/bin/env python3
# ============================================
# Prizolov Sports AI - Protocol Compiler
# Version: 3.01 (Initial Infrastructure Release)
# Author: Dm.Andreyanov
# Organization: Prizolov Market / Prizolov Lab
# Target: Automated CI/CD build for prizolov.ru
# ============================================

import sys
import os
from pathlib import Path
from grpc_tools import protoc

def compile_protocols():
    """Автоматически компилирует .proto файлы в Python gRPC модули с исправлением импортов"""
    # Определение базовых директорий проекта
    current_dir = Path(__file__).resolve().parent
    root_dir = current_dir.parent
    
    proto_dir = root_dir / "proto"
    output_dir = root_dir / "prizolov_sports_ai" / "agent_bridge"
    
    # Создаем целевую директорию, если она еще не существует
    output_dir.mkdir(parents=True, exist_ok=True)
    
    proto_file = proto_dir / "prizolov_agent.proto"
    
    if not proto_file.exists():
        print(f"[ERROR] Файл протокола не найден по адресу: {proto_file}")
        sys.exit(1)
        
    print(f"[INFO] Запуск компиляции {proto_file.name}...")
    
    # Формируем аргументы для компилятора protoc
    protoc_args = [
        "grpc_tools.protoc",
        f"--proto_path={proto_dir}",
        f"--python_out={output_dir}",
        f"--grpc_python_out={output_dir}",
        str(proto_file)
    ]
    
    # Запуск компиляции
    exit_code = protoc.main(protoc_args)
    
    if exit_code != 0:
        print("[ERROR] Ошибка при компиляции Protobuf/gRPC интерфейсов.")
        sys.exit(exit_code)
        
    print("[INFO] Компиляция успешно завершена.")
    
    # Патчинг сгенерированного grpc-файла для корректной работы абсолютных импортов в пакете
    generated_grpc_file = output_dir / "prizolov_agent_pb2_grpc.py"
    
    if generated_grpc_file.exists():
        print("[INFO] Оптимизация и исправление импортов в сгенерированном gRPC модуле...")
        with open(generated_grpc_file, "r", encoding="utf-8") as file:
            content = file.read()
            
        # Заменяем сломанный относительный импорт на корректный внутрипакетный
        broken_import = "import prizolov_agent_pb2 as prizolov__agent__pb2"
        fixed_import = "from . import prizolov_agent_pb2 as prizolov__agent__pb2"
        
        if broken_import in content:
            content = content.replace(broken_import, fixed_import)
            with open(generated_grpc_file, "w", encoding="utf-8") as file:
                file.write(content)
            print("[INFO] gRPC-импорты успешно адаптированы под архитектуру пакета.")
        else:
            print("[WARNING] Целевая строка импорта не найдена или уже модифицирована.")
            
    # Создаем __init__.py в целевой папке для превращения её в валидный Python пакет
    init_file = output_dir / "__init__.py"
    if not init_file.exists():
        with open(init_file, "w", encoding="utf-8") as file:
            file.write("# Generated by Prizolov Sports AI Compiler\n")

if __name__ == "__main__":
    compile_protocols()
