#!/usr/bin/env bash
set -euo pipefail

PROFILE="${1:-balanced}"

case "$PROFILE" in
  conservative)
    cat <<'EOF'
# Conservative profile: max stability, lower volume
MIN_BOOKMAKERS_PER_EVENT=3
MIN_RECOMMENDATION_PROBABILITY=0.56
MIN_RECOMMENDATION_COEFFICIENT=1.60
MIN_RECOMMENDATION_EDGE=0.03
MIN_EVENT_QUALITY_SCORE=55
MAX_BOOKMAKER_ODDS_AGE_SECONDS=480
MAX_RECOMMENDATIONS_PER_EVENT=5
MAX_LINES_PER_MARKET=2
MAX_CORRELATED_LINES_PER_EVENT=1
MAX_TOP_RECOMMENDATIONS_PER_EVENT=1

VALUE_ONLY_PREMIUM_ENABLED=1
VALUE_ONLY_PREMIUM_MIN_EDGE=0.08
VALUE_ONLY_PREMIUM_MIN_BOOKMAKERS_SUPPORT=3

BOOKMAKER_WEIGHT_DEFAULT=1.00
BOOKMAKER_WEIGHT_OVERRIDES={"pinnacle":1.30,"betfair":1.25,"matchbook":1.20}
SPORT_MARKET_THRESHOLD_OVERRIDES={"football":{"spreads":{"min_probability_delta":0.02,"min_edge_delta":0.01}}}

ADAPTIVE_THRESHOLD_ENABLED=1
ADAPTIVE_THRESHOLD_MIN_FEEDBACK=30
ADAPTIVE_MIN_PROBABILITY_FLOOR=0.48
ADAPTIVE_MIN_PROBABILITY_CEIL=0.74

SELF_LEARNING_ENABLED=1
SELF_LEARNING_MIN_FEEDBACK=10
SELF_LEARNING_MAX_FACTOR_SHIFT=0.20
SELF_LEARNING_DECAY_ENABLED=1
SELF_LEARNING_DECAY_HALF_LIFE_HOURS=96
CLV_ALERT_NEGATIVE_THRESHOLD=-0.03
EOF
    ;;
  balanced)
    cat <<'EOF'
# Balanced profile: default recommended production mode
MIN_BOOKMAKERS_PER_EVENT=2
MIN_RECOMMENDATION_PROBABILITY=0.50
MIN_RECOMMENDATION_COEFFICIENT=1.55
MIN_RECOMMENDATION_EDGE=0.02
MIN_EVENT_QUALITY_SCORE=46
MAX_BOOKMAKER_ODDS_AGE_SECONDS=900
MAX_RECOMMENDATIONS_PER_EVENT=6
MAX_LINES_PER_MARKET=3
MAX_CORRELATED_LINES_PER_EVENT=2
MAX_TOP_RECOMMENDATIONS_PER_EVENT=2

VALUE_ONLY_PREMIUM_ENABLED=1
VALUE_ONLY_PREMIUM_MIN_EDGE=0.06
VALUE_ONLY_PREMIUM_MIN_BOOKMAKERS_SUPPORT=2

BOOKMAKER_WEIGHT_DEFAULT=1.00
BOOKMAKER_WEIGHT_OVERRIDES={"pinnacle":1.25,"betfair":1.20}
SPORT_MARKET_THRESHOLD_OVERRIDES={"football":{"spreads":{"min_probability_delta":0.01}},"basketball":{"totals":{"min_edge_delta":0.005}}}

ADAPTIVE_THRESHOLD_ENABLED=1
ADAPTIVE_THRESHOLD_MIN_FEEDBACK=20
ADAPTIVE_MIN_PROBABILITY_FLOOR=0.42
ADAPTIVE_MIN_PROBABILITY_CEIL=0.72

SELF_LEARNING_ENABLED=1
SELF_LEARNING_MIN_FEEDBACK=8
SELF_LEARNING_MAX_FACTOR_SHIFT=0.25
SELF_LEARNING_DECAY_ENABLED=1
SELF_LEARNING_DECAY_HALF_LIFE_HOURS=168
CLV_ALERT_NEGATIVE_THRESHOLD=-0.05
EOF
    ;;
  aggressive)
    cat <<'EOF'
# Aggressive profile: higher volume, higher volatility
MIN_BOOKMAKERS_PER_EVENT=2
MIN_RECOMMENDATION_PROBABILITY=0.42
MIN_RECOMMENDATION_COEFFICIENT=1.40
MIN_RECOMMENDATION_EDGE=0.00
MIN_EVENT_QUALITY_SCORE=35
MAX_BOOKMAKER_ODDS_AGE_SECONDS=1500
MAX_RECOMMENDATIONS_PER_EVENT=8
MAX_LINES_PER_MARKET=4
MAX_CORRELATED_LINES_PER_EVENT=2
MAX_TOP_RECOMMENDATIONS_PER_EVENT=3

VALUE_ONLY_PREMIUM_ENABLED=1
VALUE_ONLY_PREMIUM_MIN_EDGE=0.03
VALUE_ONLY_PREMIUM_MIN_BOOKMAKERS_SUPPORT=2

BOOKMAKER_WEIGHT_DEFAULT=1.00
BOOKMAKER_WEIGHT_OVERRIDES={"pinnacle":1.20}
SPORT_MARKET_THRESHOLD_OVERRIDES={"football":{"totals":{"min_probability_delta":-0.01}},"basketball":{"spreads":{"min_edge_delta":-0.005}}}

ADAPTIVE_THRESHOLD_ENABLED=1
ADAPTIVE_THRESHOLD_MIN_FEEDBACK=15
ADAPTIVE_MIN_PROBABILITY_FLOOR=0.38
ADAPTIVE_MIN_PROBABILITY_CEIL=0.68

SELF_LEARNING_ENABLED=1
SELF_LEARNING_MIN_FEEDBACK=6
SELF_LEARNING_MAX_FACTOR_SHIFT=0.30
SELF_LEARNING_DECAY_ENABLED=1
SELF_LEARNING_DECAY_HALF_LIFE_HOURS=72
CLV_ALERT_NEGATIVE_THRESHOLD=-0.08
EOF
    ;;
  *)
    echo "Unknown profile: $PROFILE" >&2
    echo "Usage: $0 {conservative|balanced|aggressive}" >&2
    exit 1
    ;;
esac
